#! /bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

for STAGE in "$DIR"/*/; do
  STAGE="$(basename "$STAGE")"
  if [[ "$STAGE" =~ ^$1 ]]; then
    echo "$STAGE"
    "$DIR"/"$STAGE"/run.sh
    break
  fi
done
